version: "3.5"

services:
  homebridge:
    image: oznu/homebridge:ubuntu
    container_name: homebridge
    restart: always
    network_mode: host
    environment:
      - PGID=1002
      - PUID=1006
      - HOMEBRIDGE_CONFIG_UI=1
      - HOMEBRIDGE_CONFIG_UI_PORT=8581
      - TZ=Europe/London
    volumes:
      - ./Volumes/Configs/Homebridge:/homebridge
  nginx: 
    image: nginx:latest
    container_name: proxy
    volumes:
      - ./Volumes/NGINX/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80